import { expect, it, afterEach } from 'vitest';
import { intakeFixture, value, refused } from '../intake/fixtures.js';
import { canonical, decode } from '../../src/index.js';
import { hashBytes } from '../../src/facts/index.js';
import { operatorFixture } from '../operator/fixture.js';
import { createOperatorSurface, evaluateGenesisReplay, evaluateMinimalPath, minimalResponse, requiredMinimalDependencies } from '../../src/operator/index.js';
import { assemblyRuntimeFixture } from '../assembly/runtime-fixture.js';
import { installProduction, productionBindingSet, productionComposition } from '../assembly/production-fixture.js';
import { bootProductionAssembly, inspectProductionAssemblyBindings } from '../../src/assembly/index.js';
import { assemblyInput } from '../assembly/fixture.js';

it('V1 clean durable request renders and verified approval appends through intake',()=>{const x=operatorFixture(),s=x.surface(); expect(value(s.render(x.request.id)).fieldsEditable).toBe(false); const c=value(s.challenge(x.request.id));value(s.confirm({challenge:c,proof:'proof',decision:'approve'}));expect(x.admitted.length).toBe(1);expect(x.facts().at(-1)!.kind).toBe('intake-verified-act');});
it.each([
 ['V2 missing request',{referenceId:'missing:request'}],['V3 wrong kind',{referenceId:'machine-a:0:0'}],
 ['V4 stale digest',{submittedDigest:hashBytes('stale')}],['V5 channel attestation',{attested:true}],
 ['V6 caller valid',{extra:{valid:true}}],['V7 caller principal',{extra:{principal:{id:'alice'}}}],
 ['V8 grant editor',{extra:{grant:{actions:['work']}}}],['V9 changed rendering',{renderingDigest:hashBytes('rendering')}],
 ['V10 stale generation',{generation:{owner:'part-three',name:'RegisterGeneration',id:'stale'}}],
 ['V11 long challenge',{request:{expiresAt:1000000},challengeExpiresAt:300101}],
])('%s refuses',(_name,opts)=>{const f=intakeFixture(),v=f.verifiedAct(opts as any);refused(f.port().admitVerifiedAct(v.input));expect(f.facts().filter(r=>r.kind==='intake-verified-act')).toHaveLength(0);});
it('V12 tainted request refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.dropCapture(v.requestEvidence.reference);refused(f.port().admitVerifiedAct(v.input),'tainted');});
it('V13 concurrent request refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.conflictRequest(v);refused(f.port().admitVerifiedAct(v.input),'conflicted');});
it('V14 changed scope refuses',()=>{const f=intakeFixture(),v=f.verifiedAct({challengeScope:f.f.org});refused(f.port().admitVerifiedAct(v.input));});
it('V15 approved request cannot replay',()=>{const f=intakeFixture(),v=f.verifiedAct();expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe('approved');refused(f.port().admitVerifiedAct(v.input),'replayed');});
it('V16 declined request cannot replay',()=>{const f=intakeFixture(),v=f.verifiedAct({decision:'decline'});expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe('declined');refused(f.port().admitVerifiedAct(v.input),'replayed');});
it.each([['V17 base',{currentBase:'base:changed'}],['V18 artifact',{artifact:hashBytes('changed')}]] )('%s current mismatch refuses',(_name,change)=>{const f=intakeFixture(),v=f.verifiedAct();Object.assign(f.context,{decode:{...f.context.decode,...change}});refused(f.port().admitVerifiedAct(v.input),'current');});
it('V19 expiry boundary accepts at expiry, refuses after',()=>{for(const time of [200,201]){const f=intakeFixture(),v=f.verifiedAct();f.setTime(time); const r=f.port().admitVerifiedAct(v.input);if(time===200)expect(value(r).kind).toBe('approved');else refused(r,'expired');}});
it('V20 independent emergency stop accepts despite unavailable request capture',()=>{const f=intakeFixture();Object.assign(f.context,{decode:{...f.context.decode,register:{...f.context.decode.register,actions:{...f.context.decode.register.actions,'emergency-stop':{protected:true,repository:false}}}}});const v=f.verifiedAct({action:'emergency-stop'});f.dropCapture(v.requestEvidence.reference);expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe('emergency-stopped');});
it('V21 clean assembly resolves and boots',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f);const r=value(bootProductionAssembly({...f.composition,production:productionComposition(f,x.binding)},x.manifest.id,x.binding.scope));expect(r.references.every(r=>r.completeness==='complete')).toBe(true);});
it('V22 wrong signed dependency kind refuses',()=>{const f=assemblyRuntimeFixture(),base=productionBindingSet();const clock=base.dependencies.find(r=>r.name==='clock')!;const b={...base,dependencies:base.dependencies.map(r=>r.name==='route'?{...r,fact:clock.fact}:r)};const x=installProduction(f,b);refused(bootProductionAssembly({...f.composition,production:productionComposition(f,b)},x.manifest.id,b.scope),'conversation-route');});
it('V23 incomplete resolvable binding remains partial and refuses boot',()=>{const f=assemblyRuntimeFixture();const p=value(f.runtime.record('GrowthObservation',{...assemblyInput('GrowthObservation'),id:'partial:test',completion:'incomplete',sampleCount:0,timeouts:1}));const base=productionBindingSet();const b={...base,dependencies:base.dependencies.map(r=>r.name==='local-facts'?{...r,fact:{reference:p.id,expectedKind:'assembly-GrowthObservation',required:true}}:r)};const x=installProduction(f,b as any),c={...f.composition,production:productionComposition(f,b as any)};expect(value(inspectProductionAssemblyBindings(c,x.manifest.id,b.scope)).find(r=>r.name==='dependency:local-facts')!.completeness).toBe('partial');refused(bootProductionAssembly(c,x.manifest.id,b.scope),'partial');});
it.each(requiredMinimalDependencies.map((d,i)=>[`V${24+i}`,d]))('%s missing %s preserves owned outage and refuses response',(_id,name)=>{const f=operatorFixture();const admitted=Object.fromEntries(requiredMinimalDependencies.map(d=>[d,d!==name]));const s=value(evaluateMinimalPath({admitted:admitted as any,ordinaryUnavailable:[],inputPreserved:true,repairOwner:'repair',maximumExposure:9},f.f.c));expect(s.maximumExposure).toBe(9);expect(s.replayCount).toBe(0);refused(minimalResponse(s,{attributable:true,pending:[],blocked:[],uncertain:[],emergencyStop:false},f.f.c));});
it('V34 ordinary outage still allows honest limited response',()=>{const f=operatorFixture();const s=value(evaluateMinimalPath({admitted:Object.fromEntries(requiredMinimalDependencies.map(d=>[d,true])) as any,ordinaryUnavailable:['model'],inputPreserved:true,repairOwner:'repair',maximumExposure:9},f.f.c));expect(value(minimalResponse(s,{attributable:true,pending:['run'],blocked:['model'],uncertain:[],emergencyStop:false},f.f.c))).toContain('Limited response');});
function grantAct(expiresAt:number,recurrence='["recurred"]') {const f=intakeFixture(),v=f.verifiedAct({request:{recurrence}});const raw=f.f.grant({id:'grant:selected',grantee:f.f.bob,standing:'delegate',actions:['work'],scope:f.f.scope,expiresAt});const fields=Object.fromEntries(Object.entries(raw).filter(([k])=>!['type','schemaVersion','source'].includes(k)));const signed=f.f.proof(fields,{id:'alice',kind:'person'},'intent-approval');const act=value(decode('StandingGrant',{type:'StandingGrant',schemaVersion:1,...fields,source:signed.p},{...f.context.decode,provenance:signed.p}));const cp=f.f.proof({...v.challengePayload,actDigest:value(canonical(act)).hash},{id:'alice',kind:'person'},'verified-operator-challenge');const proof=value(f.deps.capture.preserve(JSON.stringify({type:'VerifiedActProofBundle',schemaVersion:1,challenge:cp.input,act:signed.input}),f.f.now));f.syncCaptures();return f.port().admitVerifiedAct({...v.input,act,proof});}
it('V35 exact standing grant with recurrence accepts',()=>expect(value(grantAct(400)).kind).toBe('approved'));
it('V36 standing grant without recurrence refuses',()=>refused(grantAct(400,'[]')));
it('V37 standing grant term not derived from request refuses',()=>refused(grantAct(1000000)));
it('V38 clean pending request remains readable beside conflicted request',()=>{const x=operatorFixture();x.conflictRequest();const clean=x.verifiedAct({surface:'phone-surface',request:{requestId:'clean:second'}});const s=value(createOperatorSurface({...x.composition,maxPending:10}));expect(value(s.render(clean.request.id)).requestId).toBe('clean:second');const pending=value(s.pending(10));expect(pending.rows.some(r=>r.requestId==='clean:second')).toBe(true);});
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
// @ts-expect-error The public process-restart acceptance boundary is executable JavaScript by design.
import { bootProductionSliceAssembly, sliceConfig } from '../../scripts/slice-assembly.mjs';
// @ts-expect-error Preserve the reviewer's executable case at the untyped JavaScript production boundary.

it('V39 production restart cut makes the exact route dependency unavailable',()=>{const r=bootProductionSliceAssembly({home:mkdtempSync(join(tmpdir(),'p11-r6-restart-cut-')),config:sliceConfig({profile:'reply'}),restartRecovery:true});const c=r.coordinator,ref=c.references.find(r=>r.name==='dependency:route');const input={name:'route',fact:ref.fact,completeness:ref.completeness,missing:ref.missing};expect(value(c.handles.dependencyAdmission.admit(input)).current).toBe(true);value(c.handles.lifecycle.cut('route'));refused(c.handles.dependencyAdmission.admit(input));},120000);
// @ts-expect-error Preserve the reviewer's executable case at the untyped JavaScript production boundary.
it('V40 production restart recovery preserves clean route admission',()=>{const r=bootProductionSliceAssembly({home:mkdtempSync(join(tmpdir(),'p11-r6-restart-clean-')),config:sliceConfig({profile:'reply'}),restartRecovery:true});const c=r.coordinator,ref=c.references.find(r=>r.name==='dependency:route');value(c.handles.lifecycle.recover('route'));expect(value(c.handles.dependencyAdmission.admit({name:'route',fact:ref.fact,completeness:ref.completeness,missing:ref.missing})).current).toBe(true);},120000);
import { productionOperatorSlice } from '../operator/production-slice-fixture.js';
// @ts-expect-error The public process-restart acceptance boundary is executable JavaScript by design.
import { runSliceExecution } from '../../scripts/slice-execution.mjs';
it('V41 caller-supplied unwitnessed delivery refuses',async()=>{const x=productionOperatorSlice();x.production.deliveryWitness.observe=operation=>x.assembly.success({owner:'part-nine',administration:'independent',operation,platform:x.binding.deliveryWitness.platform,stage:'service-applied',probe:{id:'not-recorded'}});await expect(x.runtime.drive()).rejects.toThrow('unwitnessed');},120000);
it('V42 clean delivery uses real assembly and the recorded Part Nine result despite changed callback prose',async()=>{const x=productionOperatorSlice();const original=x.production.deliveryWitness.observe;x.production.deliveryWitness.observe=operation=>{const r=value(original(operation)) as {probe:{comparison:string}};return x.assembly.success({...r,probe:{...r.probe,comparison:'unrecorded-callback-claim'}});};const report=await x.runtime.drive();expect(report.assemblyBoot.owner).toBe('part-ten');expect(report.externalApplications).toHaveLength(1);expect(report.independentlyWitnessedResult.probe.comparison).toBe('application:service-message:1');expect(report.verificationRecords).toContain(report.independentlyWitnessedResult.probe.id);expect(report.rebuilds.every((r: {equal:string})=>r.equal==='equal')).toBe(true);},120000);
// @ts-expect-error Preserve the reviewer's executable case at the untyped JavaScript production boundary.
it('V43 real public restart after external send and before evidence retains one witnessed outcome',async()=>{const x=await runSliceExecution({profile:'reply',cuts:['external-send','delivery-evidence'],maxBoots:12});expect(x.boots).toBeGreaterThanOrEqual(3);expect(x.report.externalApplications).toHaveLength(1);expect(x.report.independentlyWitnessedResult.operation).toBe(x.report.externalApplications[0].operation);expect(x.report.verificationRecords).toContain(x.report.independentlyWitnessedResult.probe.id);expect(x.report.rebuilds.every(r=>r.equal==='equal')).toBe(true);},240000);
it.each([['V44 requester','requesterIdentity'],['V45 effect adapter','effectAdapterIdentity']])('%s witness collision refuses',(_name,field)=>{const f=assemblyRuntimeFixture(),x=installProduction(f),p=productionComposition(f,x.binding);refused(bootProductionAssembly({...f.composition,production:{...p,[field]:p.deliveryWitness.identity}},x.manifest.id,x.binding.scope),'distinct');});
it('V46 unavailable required binding refuses clean signed references',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f),p=productionComposition(f,x.binding);value(p.lifecycle.cut('replication-peer'));refused(bootProductionAssembly({...f.composition,production:p},x.manifest.id,x.binding.scope),'cut');});
it('V47 missing production bindings refuses',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f);refused(bootProductionAssembly(f.composition,x.manifest.id,x.binding.scope),'unavailable');});

afterEach(async()=>{await new Promise<void>(done=>setImmediate(done));});
