import assert from './assertions.mjs';
import { readFileSync, writeFileSync } from 'node:fs';
import { providerFixture, value, enc } from '../fixture.ts';
import { effectFixture } from '../../effects/fixture.ts';
import { privateKey } from '../../facts/fixtures.ts';
import { localProvider } from '../http-provider.ts';
import { consumeResult, consumeOutcome } from '../../../src/index.js';
import { createEffectSettlementAssessmentPort } from '../../../src/verification/index.js';
import { createProviderEffectDoorway, registerProviderEffectBodies, providerEffectSchemas, providerEffectMigrations } from '../../../src/effects/index.js';
import { signEnvelope, decodeEnvelope, prepareSnapshot } from '../../../src/facts/index.js';
const status=r=>consumeResult(r,{Success:v=>({kind:'Success',value:v}),Refused:r=>({kind:'Refused',detail:r.detail})});
const raw=f=>f.body.record;
const count=f=>f.all().filter(f=>f.kind==='effect-provider-ProviderEffectSettlement').length;
function input(f,op){const rows=value(f.six.inspect()).filter(r=>r.record.type==='AdmissionReservation'&&r.record.operation===op);const r=rows.at(-1).record;return {request:{id:r.request,attempt:r.attempt,digest:r.digest,verificationBar:'provider-bar'},reservation:r,claim:rows.find(r=>r.record.state==='dispatch-claimed').fact.id,observations:f.all().filter(f=>f.kind==='effect-provider-ProviderOperationObservation'&&raw(f).operation===op).map(raw),plan:f.plan.id,bar:'provider-bar',generation:f.th.current().generation.id};}

async function fixture(fn){const http=await localProvider();try{const f=providerFixture(http);http.respond({state:'complete',bytes:JSON.stringify(f.decisionInput()),providerOperation:'real-http',usage:{inputTokens:1,outputTokens:1,charge:3,source:'http'},retryBlocked:false});const {prepared,request}=f.prepare();const observed=value(await f.api.dispatch(request,f.fence));return await fn(f,request,observed,prepared,http);}finally{await http.close();}}
function proof(f,q,o){f.evidence(o.operation,q.digest,'operation-occurred');f.evidence(o.operation,q.digest,'charge-settled',3);f.evidence(o.operation,q.digest,'old-executor-quiescent');}
export function registerCases(test) {
for(const field of ['taints','captureStatuses','predecessors']) test('V18-'+field,'inconsistent signed assessment '+field+' must not reach settlement or accounting',()=>fixture((f,q,o)=>{proof(f,q,o);const runtime={...f.runtime,record:(name,v)=>f.runtime.record(name,name==='VerificationAssessment'?{...v,[field]:field==='taints'?['contested']:[]}:v)};const port=createEffectSettlementAssessmentPort(f.vh,runtime,f.store),a=value(port.assess(input(f,o.operation)));const out=status(f.api.settle(o.operation,a));const accounting=out.kind==='Success'?status(f.six.settle(f.fence,out.value)):null;assert.equal(out.kind,'Refused',JSON.stringify({settlements:count(f),accounting}));assert.equal(count(f),0);assert.equal(f.all().filter(f=>f.kind==='transport-SettlementApplication').length,0);return out;}));
test('V19','missing wrong-kind unavailable and incomplete references refuse; exact neighbor accepts',()=>fixture((f,q,o)=>{proof(f,q,o);const a=value(f.api.assess(o.operation)),i=input(f,o.operation),entries=[];for(const [label,ref,altered] of [['missing',{...a,id:'missing'},i],['wrong-kind',{...a,id:f.all().find(f=>f.kind==='verification-VerificationPlan').id},i],['wrong-owner',{...a,owner:'part-eight'},i],['incomplete-observations',a,{...i,observations:i.observations.slice(1)}],['wrong-claim',a,{...i,claim:f.opening.id}]]){const out=status(f.nine.consumeEffectSettlementAssessment(ref,altered,()=>true));assert.equal(out.kind,'Refused',label);entries.push({label,...out});}let positive=status(f.nine.consumeEffectSettlementAssessment(a,i,()=>true));assert.equal(positive.kind,'Success');const cap=i.observations[0].capture;const backup=f.metadata[cap.reference];f.metadata[cap.reference]={...backup,status:'missing',bytes:null};const out=status(f.nine.consumeEffectSettlementAssessment(a,i,()=>true));assert.equal(out.kind,'Refused');f.metadata[cap.reference]=backup;positive=status(f.nine.consumeEffectSettlementAssessment(a,i,()=>true));assert.equal(positive.kind,'Success');return entries;}));
test('V20','honestly partial occurrence keeps charge and delayed-execution unresolved',()=>fixture((f,q,o)=>{f.evidence(o.operation,q.digest,'operation-occurred');const s=value(f.api.settle(o.operation,value(f.api.assess(o.operation))));assert.equal(s.finalCharge,null);assert.equal(s.delayedExecutionExcluded,false);assert.equal(s.retainedExposure,20);const a=value(f.six.settle(f.fence,s));assert.equal(a.released,0);assert.equal(a.retryEligible,0);return a;}));
test('V21','new signed observation during settlement guard refuses before settlement append',()=>fixture((f,q,o)=>{proof(f,q,o);const a=value(f.api.assess(o.operation));const original=f.host.capture;let fired=false;f.host.capture=bytes=>{if(!fired){fired=true;const all=f.all(),last=all.at(-1);const segment={...last.segment,position:last.segment.position+1};const record={...o,id:'later-observation'};const fact=signEnvelope({...last,id:`${segment.machine}:${segment.epoch}:${segment.position}`,segment,prevInSegment:last.contentHash,predecessors:{inSegment:last.id,frontier:{},required:[q.payload.prepared.id]},kind:'effect-provider-ProviderOperationObservation',schemaVersion:1,body:{record}},privateKey);value(f.store.append(fact,{peer:'machine-a'}));}return original(bytes);};const out=status(f.api.settle(o.operation,a));assert.equal(out.kind,'Refused');assert.equal(count(f),0,JSON.stringify({out,settlements:count(f)}));return out;}));

}
