// @ts-nocheck -- executable reviewer cases intentionally retain their original dynamic harness shapes.
import { groundedAssemblyRuntimeFixture, genuineProductionComposition, installProduction } from '../assembly/genuine-production-fixture.js';
import { afterEach, beforeEach, expect, it } from 'vitest';
import { consumeResult, canonical, decode, defineDecoder } from '../../src/index.js';
import { hashBytes } from '../../src/facts/index.js';
import { createIntakePort, classifySlicePayload } from '../../src/intake/index.js';
import { bootProductionAssembly, inspectProductionAssemblyBindings } from '../../src/assembly/index.js';
import { evaluateMinimalPath, minimalResponse, requiredMinimalDependencies, evaluateGenesisReplay, minimalPlaneProjections, createOperatorSurface } from '../../src/operator/index.js';
import { intakeFixture, value, message, route } from '../intake/fixtures.js';
import { operatorFixture } from '../operator/fixture.js';
import { assemblyRuntimeFixture } from '../assembly/round8-extended-fixture.js';
import { productionBindingSet, productionComposition } from '../assembly/production-fixture.js';
import { assemblyInput } from '../assembly/fixture.js';
import { productionOperatorSlice } from '../operator/production-slice-fixture.js';
beforeEach(() => new Promise<void>(resolve => setImmediate(resolve)));
afterEach(() => new Promise<void>(resolve => setImmediate(resolve)));
const outcome = (r:any):any => consumeResult(r,{Success:(v:any)=>({accepted:true,value:v}),Refused:(r:any)=>({accepted:false,detail:r.detail})});
function check(id:string,title:string,fn:()=>any){it(`${id} ${title}`,fn,300_000);}
const yes=(r:any)=>{const o=outcome(r);expect(o.accepted,JSON.stringify(o)).toBe(true);return o;};
const no=(r:any)=>{const o=outcome(r);expect(o.accepted,JSON.stringify(o)).toBe(false);return o;};
check('V1','clean verified approval resolves and appends one owner disposition',()=>{const f=intakeFixture(),v=f.verifiedAct();const o=yes(f.port().admitVerifiedAct(v.input));expect(o.value.kind).toBe('approved');expect(f.facts().filter(r=>r.kind==='intake-verified-act')).toHaveLength(1);return o;});
const badIntake:any[]=[
 ['V2','missing request',{referenceId:'missing'}],['V3','wrong-kind request',{referenceId:'machine-a:0:0'}],
 ['V4','stale digest',{submittedDigest:hashBytes('stale')}],['V5','channel-attested challenge',{attested:true}],
 ['V6','caller valid true',{extra:{valid:true}}],['V7','caller principal',{extra:{principal:{id:'alice'}}}],
 ['V8','caller grant fields',{extra:{grant:{actions:['work']}}}],['V9','altered signed rendering',{renderingDigest:hashBytes('changed')}],
 ['V10','stale generation',{generation:{owner:'part-three',name:'RegisterGeneration',id:'old'}}],
 ['V11','future challenge',{challengeIssuedAt:101}],['V12','expired challenge',{challengeExpiresAt:99}],
 ['V13','excess challenge lifetime',{request:{expiresAt:1000000},challengeExpiresAt:300101}]
];
for(const [id,title,opts] of badIntake)check(id,title,()=>{const f=intakeFixture(),v=f.verifiedAct(opts);const o=no(f.port().admitVerifiedAct(v.input));expect(f.facts().some(r=>r.kind==='intake-verified-act')).toBe(false);return o;});
check('V14','wrong scope with otherwise signed act refuses',()=>{const f=intakeFixture();const scope=value(decode('Scope',{type:'Scope',schemaVersion:1,kind:'project',members:['project-b']},f.context.decode));return no(f.port().admitVerifiedAct(f.verifiedAct({challengeScope:scope}).input));});
check('V15','missing request evidence refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.dropCapture(v.requestEvidence.reference);return no(f.port().admitVerifiedAct(v.input));});
check('V16','concurrent request refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.conflictRequest(v);return no(f.port().admitVerifiedAct(v.input));});
check('V17','replay on fresh intake port refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();yes(f.port().admitVerifiedAct(v.input));return no(f.port().admitVerifiedAct(v.input));});
check('V18','clean decline accepted once',()=>{const f=intakeFixture(),v=f.verifiedAct({decision:'decline'});expect(yes(f.port().admitVerifiedAct(v.input)).value.kind).toBe('declined');return no(f.port().admitVerifiedAct(v.input));});
for(const [id,key,val] of [['V19','currentBase','base:moved'],['V20','artifact',hashBytes('moved')]])check(id,'current '+key+' mismatch refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();Object.assign(f.context,{decode:{...f.context.decode,[key]:val}});return no(f.port().admitVerifiedAct(v.input));});
for(const [id,key,val] of [['V21','audience','wrong'],['V22','operator','carol'],['V23','requestedBy','carol'],['V24','action','reply']])check(id,'independently signed wrong '+key+' refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();const signed=f.f.proof({...v.challengePayload,[key]:val},{id:'alice',kind:'person'},'verified-operator-challenge');const proof=value(f.deps.capture.preserve(JSON.stringify({type:'VerifiedActProofBundle',schemaVersion:1,challenge:signed.input,act:v.actProof}),f.f.now));f.syncCaptures();return no(f.port().admitVerifiedAct({...v.input,proof}));});
check('V25','same challenge cannot dispose a different request',()=>{const f=intakeFixture(),a=f.verifiedAct({challengeId:'one',request:{requestId:'one'}}),b=f.verifiedAct({challengeId:'one',request:{requestId:'two'}});yes(f.port().admitVerifiedAct(a.input));return no(f.port().admitVerifiedAct(b.input));});
check('V26','surface renders durable system fields and immutable requester region',()=>{const f=operatorFixture(),v=yes(f.surface().render(f.request.id)).value;expect(v.requestDigest).toBe(f.requestBody.requestDigest);expect(v.fieldsEditable).toBe(false);expect(v.requesterText.label).toContain('UNTRUSTED');expect(v.primaryActions).toEqual(['approve','decline']);return v;});
check('V27','surface exact clean confirmation delegates to Part Four',()=>{const f=operatorFixture(),s=f.surface();const o=yes(s.confirm({challenge:value(s.challenge(f.request.id)),proof:'verified',decision:'approve'}));expect(f.admitted).toHaveLength(1);return o;});
check('V28','surface changed challenge refuses before disposition',()=>{const f=operatorFixture(),s=f.surface();const c=value(s.challenge(f.request.id));return no(s.confirm({challenge:{...c,audience:'elsewhere'},proof:'verified',decision:'approve'}));});
check('V29','independent stop accepts during concurrent binding conflict',()=>{const f=operatorFixture();f.bind();f.bind({sender:'other',identityEpoch:'other'});const s=f.surface(),c=value(s.stopChallenge({operator:'alice',scope:f.f.scope}));const o=yes(s.stop({challenge:c,proof:'verified',scope:f.f.scope}));expect(f.stopped).toHaveLength(1);return o;});
check('V30','ordinary receive recover expire and stop remain usable after historical approval and base advance',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();yes(p.receive(message('before'),route));const receipt=f.facts().find(r=>r.kind==='intake-receipt')!;yes(p.admitVerifiedAct(v.input));Object.assign(f.context,{decode:{...f.context.decode,currentBase:'base:2',artifact:hashBytes('new')}});expect(yes(p.recover(receipt.id)).value.kind).toBe('duplicate');expect(yes(p.expireHolds()).value).toBe(0);expect(yes(p.receive(message('after'),{...route,eventId:'after'})).value.kind).toBe('admitted');expect(yes(p.receive(JSON.stringify({schemaVersion:1,kind:'stop',command:'/stop'}),{...route,eventId:'stop'})).value.kind).toBe('stopped');});
check('V31','legacy schema configuration still constructs and admits requester messages',()=>{const f=intakeFixture();Object.assign(f.context,{schemas:f.context.schemas.filter(r=>!['authorization-request','intake-verified-act'].includes(r.kind))});return yes(value(createIntakePort(f.deps)).receive(message(),route));});
check('V32','requester protocol refuses authority-shaped payloads and accepts clean neighbor',()=>{expect(classifySlicePayload({schemaVersion:1,kind:'message',text:'hello'}).kind).toBe('conversation');for(const p of [{schemaVersion:1,kind:'message',text:'hello',valid:true},{schemaVersion:1,kind:'message',text:'hello',grant:{}},{schemaVersion:1,kind:'Authorization'},{schemaVersion:1,kind:'stop',command:'/stop',principal:'alice'}])expect(classifySlicePayload(p).kind).toBe('needs-judgment');});
function assembly(){const f=assemblyRuntimeFixture(),b=productionBindingSet(),i=installProduction(f,b),p=productionComposition(f,b);return{f,b,i,p,boot:()=>bootProductionAssembly({...f.composition,production:p},i.manifest.id,b.scope)};}
check('V33','well-formed assembly resolves every binding',()=>{const f=groundedAssemblyRuntimeFixture(),b=productionBindingSet(),i=installProduction(f,b),p=genuineProductionComposition(f,b),a={boot:()=>bootProductionAssembly({...f.composition,production:p},i.manifest.id,b.scope)},o=yes(a.boot());expect(o.value.references).toHaveLength(24);expect(o.value.references.every((r:any)=>r.completeness==='complete')).toBe(true);return {references:o.value.references.length};});
check('V34','wrong-kind route reference refuses even when caller expects that wrong kind',()=>{const f=assemblyRuntimeFixture(),base=productionBindingSet();const b={...base,dependencies:base.dependencies.map(r=>r.name==='route'?{...r,fact:base.dependencies.find(r=>r.name==='clock')!.fact}:r)},i=installProduction(f,b);return no(bootProductionAssembly({...f.composition,production:productionComposition(f,b)},i.manifest.id,b.scope));});
check('V35','missing signed route refuses',()=>{const a=assembly();const n=a.f.raw.findIndex((r:any)=>r.kind==='conversation-route');a.f.raw.splice(n,1);return no(a.boot());});
check('V36','missing verifier operation refuses',()=>{const a=assembly();a.p.challengeVerifier.port.verify=null as never;return no(a.boot());});
check('V37','partial resolvable binding retained without boot promotion',()=>{const f=assemblyRuntimeFixture(),partial=value(f.runtime.record('GrowthObservation',{...assemblyInput('GrowthObservation'),id:'partial-binding',completion:'incomplete',sampleCount:0,timeouts:1})),base=productionBindingSet();const b={...base,dependencies:base.dependencies.map(r=>r.name==='local-facts'?{...r,fact:{reference:partial.id,expectedKind:'assembly-GrowthObservation',required:true as const}}:r)},i=installProduction(f,b),c={...f.composition,production:productionComposition(f,b)};const rows=yes(inspectProductionAssemblyBindings(c,i.manifest.id,b.scope)).value;expect(rows.find((r:any)=>r.name==='dependency:local-facts').completeness).toBe('partial');return no(bootProductionAssembly(c,i.manifest.id,b.scope));});
for(const [id,collision] of [['V38','requesterIdentity'],['V39','surface'],['V40','effectAdapterIdentity']])check(id,'delivery witness distinct from '+collision,()=>{const a=assembly();Object.assign(a.p.deliveryWitness,{identity:collision==='surface'?a.p.surface.id:(a.p as any)[collision]});return no(a.boot());});
check('V41','posture missing witness renders unprotected',()=>{const f=operatorFixture(),o=yes(f.surface().protection('op','path'));expect(o.value.posture).toBe('unprotected');return o;});
let number=42;
for(const dependency of requiredMinimalDependencies){const id='V'+number++;check(id,dependency+' absence preserves owned outage and refuses response',()=>{const f=operatorFixture();const admitted=Object.fromEntries(requiredMinimalDependencies.map(n=>[n,n!==dependency])) as any;const state=yes(evaluateMinimalPath({admitted,ordinaryUnavailable:[],inputPreserved:true,repairOwner:'repair',maximumExposure:10},f.f.c)).value;expect(state.responseEligible).toBe(false);expect(state.maximumExposure).toBe(10);expect(state.replayCount).toBe(0);return no(minimalResponse(state,{attributable:true,pending:[],blocked:[],uncertain:[],emergencyStop:false},f.f.c));});}
check('V52','ordinary dependency loss permits limited response with complete minimal prerequisites',()=>{const f=operatorFixture(),admitted=Object.fromEntries(requiredMinimalDependencies.map(n=>[n,true])) as any;const state=yes(evaluateMinimalPath({admitted,ordinaryUnavailable:['model','business-effect','ordinary-worker'],inputPreserved:true,repairOwner:'repair',maximumExposure:10},f.f.c)).value;return yes(minimalResponse(state,{attributable:true,pending:['model'],blocked:[],uncertain:[],emergencyStop:false},f.f.c));});
check('V53','six informational projections declare every source kind',()=>{const kinds=['intake-receipt','authorization-request','intake-verified-act','new-source-kind'];const defs=minimalPlaneProjections(kinds);expect(defs).toHaveLength(6);for(const d of defs){expect(d.class).toBe('informational');expect(Object.keys(d.decisions).sort()).toEqual([...kinds].sort());}});
const samples=['cold','warm'].map(cache=>({deployment:'local',cache,facts:10,bytes:100,lineages:1,generation:'gen',started:10,ended:20,peakMemory:100,resultDigest:hashBytes('same'),failures:[]}));
check('V54','complete measured cold/warm samples accepted',()=>{const f=operatorFixture();const o=yes(evaluateGenesisReplay(samples as any,{local:['cold','warm']},20,1,1,f.f.c,200));expect(o.value.eligible).toBe(true);return o;});
for(const [id,title,change] of [['V55','warm-only',(s:any[])=>s.slice(1)],['V56','failed sample',(s:any[])=>[s[0],{...s[1],failures:['timeout']}]],['V57','changed canonical bytes',(s:any[])=>[s[0],{...s[1],resultDigest:hashBytes('different')}]],['V58','memory over budget',(s:any[])=>[s[0],{...s[1],peakMemory:300}]] ] as const)check(id,title+' blocks replay admission',()=>{const f=operatorFixture(),o=yes(evaluateGenesisReplay(change(samples) as any,{local:['cold','warm']},20,1,1,f.f.c,200));expect(o.value.eligible).toBe(false);return o;});
check('V59','real composition slice accepts exact current independent evidence',async()=>{const f=productionOperatorSlice();const r=await f.runtime.drive();expect(r.independentlyWitnessedResult.stage).toBe('service-applied');expect(r.externalApplications).toHaveLength(1);expect(r.rebuilds.every((x:any)=>x.equal==='equal')).toBe(true);return {operation:r.outbound.operation,result:r.independentlyWitnessedResult,applications:r.externalApplications.length};});
for(const [id,mode] of [['V60','missing'],['V61','stale'],['V62','wrong-stage'],['V63','wrong-operation']])check(id,mode+' independent delivery evidence refuses displayed success',async()=>{const f=productionOperatorSlice(),observe=f.production.deliveryWitness.observe;f.production.deliveryWitness.observe=(operation=>{const r=observe(operation);if(mode==='missing')f.verification.setEvidence([]);if(mode==='stale')f.verification.time(1000);if(mode==='wrong-stage')return f.assembly.success({...value(r),stage:'reader-read'});if(mode==='wrong-operation')return f.assembly.success({...value(r),operation:'different'});return r;}) as any;await expect(f.runtime.drive()).rejects.toThrow('unwitnessed');expect(f.runtime.service.journal().applications).toHaveLength(1);});
check('V64','R9-F1 live dependency that changes to current false after boot prevents slice dispatch',async()=>{const f=productionOperatorSlice(),admit=f.production.dependencyAdmission.admit;f.production.dependencyAdmission.admit=(input=>{const r=admit(input);return input.name==='route'?f.assembly.success({...value(r),current:false}):r;}) as any;const report=await f.runtime.drive();const actual={applications:f.runtime.service.journal().applications.length,stage:report?.independentlyWitnessedResult?.stage};expect(actual.applications,JSON.stringify(actual)).toBe(0);expect(report.preservedInput).toBeTruthy();expect(report.obligations).toContainEqual(expect.objectContaining({state:'owned-pending-prerequisite-outage',owner:'part-ten'}));return actual;});
check('V65','R9-F2 assembly refuses missing required verification posture operation',()=>{const f=assemblyRuntimeFixture(),b=productionBindingSet(),i=installProduction(f,b),p=productionComposition(f,b);p.verification.port.posture=undefined as never;return no(bootProductionAssembly({...f.composition,production:p},i.manifest.id,b.scope));});
check('V66','boot refuses stale route handle as positive refusal control for V64',()=>{const f=assemblyRuntimeFixture(),b=productionBindingSet(),i=installProduction(f,b),p=productionComposition(f,b),admit=p.dependencyAdmission.admit;p.dependencyAdmission.admit=(input=>input.name==='route'?f.success({...value(admit(input)),current:false}):admit(input)) as any;return no(bootProductionAssembly({...f.composition,production:p},i.manifest.id,b.scope));});
check('V67','R9-F1 signed required route removed after boot prevents dispatch',async()=>{const f=productionOperatorSlice();const n=f.assembly.raw.findIndex((r:any)=>r.kind==='conversation-route');expect(n).toBeGreaterThanOrEqual(0);f.assembly.raw.splice(n,1);const report=await f.runtime.drive();const actual={applications:f.runtime.service.journal().applications.length,stage:report?.independentlyWitnessedResult?.stage};expect(actual.applications,JSON.stringify(actual)).toBe(0);expect(report.preservedInput).toBeTruthy();expect(report.obligations).toContainEqual(expect.objectContaining({state:'owned-pending-prerequisite-outage',owner:'part-ten'}));return actual;});
check('V68','R9-F4 broker unavailable returns explicit unprotected status while stop stays available',()=>{const f=operatorFixture();const decoder=value(defineDecoder({name:'AstraBrokerRead',owner:'astra-fixture',currentVersion:1,migrations:{},versions:{1:{validate:v=>({ok:true,value:v})}},decodeCurrent:()=>({ok:false,reason:'integrity',detail:'broker evidence service unavailable'})},f.f.c.preserved));const s=value(createOperatorSurface({...f.composition,broker:{...f.composition.broker,query:()=>decoder.decode({type:'AstraBrokerRead',schemaVersion:1},f.f.c) as any}}));const status=outcome(s.protection('operation','path'));yes(s.stop({challenge:value(s.stopChallenge({operator:'alice',scope:f.f.scope})),proof:'independent',scope:f.f.scope}));expect(f.stopped).toHaveLength(1);expect(status.accepted,JSON.stringify(status)).toBe(true);expect(status.value.posture).toBe('unprotected');expect(status.value.uncertainty).toContain('broker-evidence-unavailable:broker evidence service unavailable');return status;});
check('V69','R9-F3 Part One and Four accept independently approved request from channel-attested requester and surface renders it',()=>{
 const f=operatorFixture(),requester=f.f.principal('human-requester','person',true);f.syncCaptures();
 const v=f.verifiedAct({surface:'phone-surface',request:{requestId:'channel-requester',requestedById:requester.id}});
 const fields=Object.fromEntries(Object.entries(v.act).filter(([k])=>!['type','schemaVersion','explicitYes'].includes(k)));fields.requestedBy=requester;
 const signed=f.f.proof(fields,{id:'alice',kind:'person'},'approval',false,'phone-surface');
 const act=value(decode('Authorization',{type:'Authorization',schemaVersion:1,...fields,explicitYes:signed.p},{...f.context.decode,provenance:signed.p,now:f.f.now,actAt:f.f.now}));
 const challenge=f.f.proof({...v.challengePayload,actDigest:value(canonical(act)).hash},{id:'alice',kind:'person'},'verified-operator-challenge',false,'phone-surface');
 const proof=value(f.deps.capture.preserve(JSON.stringify({type:'VerifiedActProofBundle',schemaVersion:1,challenge:challenge.input,act:signed.input}),f.f.now));f.syncCaptures();
 const history={...f.history,decode:()=>({...f.history.decode(),principals:[...f.history.decode().principals,requester]})};
 const surface=value(createOperatorSurface({...f.composition,history}));
 const renderedBefore=outcome(surface.render(v.request.id));
 const intake=yes(f.port().admitVerifiedAct({...v.input,act,proof}));expect(intake.value.kind).toBe('approved');
 expect(renderedBefore.accepted,JSON.stringify(renderedBefore)).toBe(true);return renderedBefore;
});
check('V70','empty present requester prose remains accepted',()=>{const f=operatorFixture(),v=f.verifiedAct({surface:'phone-surface',request:{requestId:'empty',requesterProse:''}});expect(yes(f.surface().render(v.request.id)).value.requesterText.text).toBe('');return yes(f.port().admitVerifiedAct(v.input));});
