import { beforeEach, expect, it } from 'vitest';
import { hashBytes } from '../../src/facts/index.js';
import { evaluateGenesisReplay, evaluateMinimalPath, minimalResponse, requiredMinimalDependencies } from '../../src/operator/index.js';
import { bootProductionAssembly, inspectProductionAssemblyBindings } from '../../src/assembly/index.js';
import { intakeFixture, message, refused, route, value } from '../intake/fixtures.js';
import { operatorFixture } from '../operator/fixture.js';
import { assemblyRuntimeFixture } from '../assembly/runtime-fixture.js';
import { assemblyInput } from '../assembly/fixture.js';
import { installProduction, productionBindingSet, productionComposition } from '../assembly/production-fixture.js';

// Several production-assembly refusal cases are synchronously CPU-bound. Give
// Vitest's worker RPC one turn between cases so already-sent task updates cannot
// age past its fixed 60-second acknowledgement deadline.
beforeEach(() => new Promise<void>(resolve => setImmediate(resolve)));

it('V1 clean surface uses durable rendering and Part Four disposition',()=>{const f=operatorFixture(),s=f.surface();const view=value(s.render(f.request.id));expect(view.fieldsEditable).toBe(false);expect(view.requesterText.label).toBe('UNTRUSTED REQUESTER TEXT');const c=value(s.challenge(f.request.id));value(s.confirm({challenge:c,proof:'verified',decision:'approve'}));expect(f.admitted).toHaveLength(1);expect(f.facts().at(-1)!.kind).toBe('intake-verified-act');});
it.each([
  ['V2 missing request',{referenceId:'missing:request'}],['V3 wrong kind',{referenceId:'machine-a:0:0'}],
  ['V4 stale digest',{submittedDigest:hashBytes('stale')}],['V5 channel attestation',{attested:true}],
  ['V6 valid flag',{extra:{valid:true}}],['V7 caller principal',{extra:{principal:{id:'alice'}}}],
  ['V8 free form grant',{extra:{grant:{actions:['work']}}}],['V9 wrong rendering',{renderingDigest:hashBytes('rendering')}],
  ['V10 stale generation',{generation:{owner:'part-three',name:'RegisterGeneration',id:'stale'}}],
  ['V11 excessive challenge lifetime',{request:{expiresAt:1000000},challengeExpiresAt:300101}],
])('%s refuses',(_name,opts)=>{const f=intakeFixture(),v=f.verifiedAct(opts as never);refused(f.port().admitVerifiedAct(v.input));expect(f.facts().filter(r=>r.kind==='intake-verified-act')).toHaveLength(0);});
it('V12 tainted capture refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.dropCapture(v.requestEvidence.reference);refused(f.port().admitVerifiedAct(v.input),'tainted');});
it('V13 conflicting request refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();f.conflictRequest(v);refused(f.port().admitVerifiedAct(v.input),'conflicted');});
it('V14 scope mismatch refuses',()=>{const f=intakeFixture(),v=f.verifiedAct({challengeScope:f.f.org});refused(f.port().admitVerifiedAct(v.input));});
it.each([['V15 approve','approve','approved'],['V16 decline','decline','declined']] as const)('%s accepted once then replay refused',(_name,decision,kind)=>{const f=intakeFixture(),v=f.verifiedAct({decision});expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe(kind);refused(f.port().admitVerifiedAct(v.input),'replayed');});
it.each([['V17 base',{currentBase:'base:changed'}],['V18 artifact',{artifact:hashBytes('changed')}]] )('%s mismatch refuses',(_name,change)=>{const f=intakeFixture(),v=f.verifiedAct();Object.assign(f.context,{decode:{...f.context.decode,...change}});refused(f.port().admitVerifiedAct(v.input),'current');});
it('V19 exact expiry accepts; one tick later refuses',()=>{for(const n of [200,201]){const f=intakeFixture(),v=f.verifiedAct();f.setTime(n);if(n===200)expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe('approved');else refused(f.port().admitVerifiedAct(v.input),'expired');}});
it('V20 verified stop accepts despite unavailable request evidence',()=>{const f=intakeFixture();Object.assign(f.context,{decode:{...f.context.decode,register:{...f.context.decode.register,actions:{...f.context.decode.register.actions,'emergency-stop':{protected:true,repository:false}}}}});const v=f.verifiedAct({action:'emergency-stop'});f.dropCapture(v.requestEvidence.reference);expect(value(f.port().admitVerifiedAct(v.input)).kind).toBe('emergency-stopped');});
it('V21 clean assembly boots 24 complete references',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f);const r=value(bootProductionAssembly({...f.composition,production:productionComposition(f,x.binding)},x.manifest.id,x.binding.scope));expect(r.references).toHaveLength(24);expect(r.references.every(row=>row.completeness==='complete')).toBe(true);});
it('V22 route declared as clock is refused by fixed role kind',()=>{const f=assemblyRuntimeFixture(),b=productionBindingSet();const c=b.dependencies.find(row=>row.name==='clock')!;const changed={...b,dependencies:b.dependencies.map(row=>row.name==='route'?{...row,fact:c.fact}:row)};const x=installProduction(f,changed);refused(bootProductionAssembly({...f.composition,production:productionComposition(f,changed)},x.manifest.id,b.scope),'conversation-route');});
it('V23 resolvable partial stays visible and refuses boot',()=>{const f=assemblyRuntimeFixture(),b=productionBindingSet();const p=value(f.runtime.record('GrowthObservation',{...assemblyInput('GrowthObservation'),id:'partial:review',completion:'incomplete',sampleCount:0,timeouts:1}));const changed={...b,dependencies:b.dependencies.map(row=>row.name==='local-facts'?{...row,fact:{reference:p.id,expectedKind:'assembly-GrowthObservation',required:true as const}}:row)};const x=installProduction(f,changed),c={...f.composition,production:productionComposition(f,changed)};expect(value(inspectProductionAssemblyBindings(c,x.manifest.id,b.scope)).find(row=>row.name==='dependency:local-facts')!.completeness).toBe('partial');refused(bootProductionAssembly(c,x.manifest.id,b.scope),'partial');});
it.each(['render','pending','challenge','confirm','binding','protection','stopChallenge','stop'])('V24 missing surface method %s refuses',name=>{const f=assemblyRuntimeFixture(),x=installProduction(f),p=productionComposition(f,x.binding);refused(bootProductionAssembly({...f.composition,production:{...p,surface:{...p.surface,[name]:undefined}} as never},x.manifest.id,x.binding.scope),name);});
it.each(['principal:requester','surface:phone','adapter:telegram'])('V25 witness identity collision %s refuses',identity=>{const f=assemblyRuntimeFixture(),x=installProduction(f),p=productionComposition(f,x.binding);refused(bootProductionAssembly({...f.composition,production:{...p,deliveryWitness:{...p.deliveryWitness,identity}}},x.manifest.id,x.binding.scope));});
it.each(requiredMinimalDependencies)('V26 missing %s retains input and exposure, prevents response',dep=>{const f=operatorFixture();const admitted=Object.fromEntries(requiredMinimalDependencies.map(name=>[name,name!==dep]));const state=value(evaluateMinimalPath({admitted:admitted as never,ordinaryUnavailable:[],inputPreserved:true,repairOwner:'repair:review',maximumExposure:17},f.f.c));expect(state).toMatchObject({admitted:false,preserved:true,maximumExposure:17,replayCount:0});refused(minimalResponse(state,{attributable:true,pending:[],blocked:[],uncertain:[],emergencyStop:false},f.f.c));});
it('V27 ordinary outage admits honest limited response',()=>{const f=operatorFixture();const state=value(evaluateMinimalPath({admitted:Object.fromEntries(requiredMinimalDependencies.map(name=>[name,true])) as never,ordinaryUnavailable:['model','ordinary-worker'],inputPreserved:true,repairOwner:'repair:review',maximumExposure:17},f.f.c));expect(value(minimalResponse(state,{attributable:true,pending:['work'],blocked:[],uncertain:[],emergencyStop:false},f.f.c))).toContain('pending: work');refused(minimalResponse(state,{attributable:false,pending:[],blocked:[],uncertain:[],emergencyStop:false},f.f.c));});
it('V28 superseded request refuses; clean successor remains visible',()=>{const f=operatorFixture(),next=f.verifiedAct({surface:'phone-surface',request:{requestId:'request:1'}}),s=f.surface();refused(s.render(f.request.id));expect(value(s.pending(2)).rows.map(row=>row.fact)).toEqual([next.request.id]);});

it('V29 ordinary receive and recover accept around verified approval',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();expect(value(p.receive(message('before'),route)).kind).toBe('admitted');const receipt=f.facts().find(r=>r.kind==='intake-receipt')!;value(p.admitVerifiedAct(v.input));expect(value(p.receive(message('after'),{...route,eventId:'review:after'})).kind).toBe('admitted');expect(value(p.recover(receipt.id)).kind).toBe('duplicate');expect(value(p.expireHolds())).toBe(0);});
it('V30 valid historical approval does not block ordinary input after current base changes',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();value(p.admitVerifiedAct(v.input));Object.assign(f.context,{decode:{...f.context.decode,currentBase:'base:2'}});expect(value(p.receive(message('ordinary after base moved'),route)).kind).toBe('admitted');});
it('V31 valid historical approval does not block ordinary input after expiry',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();value(p.admitVerifiedAct(v.input));f.setTime(501);expect(value(p.receive(message('ordinary after expiry'),route)).kind).toBe('admitted');});
it('V32 ordinary input after base change accepts without an approval in history',()=>{const f=intakeFixture();f.bind();Object.assign(f.context,{decode:{...f.context.decode,currentBase:'base:2'}});expect(value(f.port().receive(message('clean ordinary input'),route)).kind).toBe('admitted');});
it('V33 ordinary recovery after recorded approval and base change stays usable',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();value(p.receive(message('ordinary before change'),route));const receipt=f.facts().find(r=>r.kind==='intake-receipt')!;value(p.admitVerifiedAct(v.input));Object.assign(f.context,{decode:{...f.context.decode,currentBase:'base:2'}});expect(value(p.recover(receipt.id)).kind).toBe('duplicate');});
it('V34 recorded approval and artifact change must not block ordinary input',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();value(p.admitVerifiedAct(v.input));Object.assign(f.context,{decode:{...f.context.decode,artifact:hashBytes('new artifact')}});expect(value(p.receive(message('ordinary after artifact change'),route)).kind).toBe('admitted');});

it.each([
  ['V39 complete cold warm replay',{},true],['V40 divergent digest',{resultDigest:hashBytes('different')},false],
  ['V41 omitted lineage',{lineages:0},false],['V42 failure sample',{failures:['timeout']},false],
  ['V43 memory over budget',{peakMemory:1001},false],['V44 duration over budget',{ended:1001},false],
  ['V45 generation mismatch',{generation:'other-generation'},false],['V46 population mismatch',{facts:101},false],
])('%s',(_name,change,eligible)=>{const f=operatorFixture(),sample={deployment:'review-hardware',cache:'cold',facts:100,bytes:4096,lineages:1,generation:'review-generation',started:1,ended:10,peakMemory:10,resultDigest:hashBytes('canonical-bytes'),failures:[]};const samples=[sample,{...sample,cache:'warm',...change}];expect(value(evaluateGenesisReplay(samples as never,{'review-hardware':['cold','warm']},100,1,1,f.f.c,1000)).eligible).toBe(eligible);});

it('V47 recorded approval history allows ordinary expiry maintenance after base change',()=>{const f=intakeFixture(),v=f.verifiedAct(),p=f.port();value(p.admitVerifiedAct(v.input));Object.assign(f.context,{decode:{...f.context.decode,currentBase:'base:2'}});expect(value(p.expireHolds())).toBe(0);});
it('V48 boot refuses a missing production binding set',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f);refused(bootProductionAssembly(f.composition,x.manifest.id,x.binding.scope),'unavailable');});
it('V49 boot refuses unavailable peer; restored peer accepts',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f),p=productionComposition(f,x.binding);const q={...p,dependencyAdmission:{...p.dependencyAdmission,admit:(input: Parameters<typeof p.dependencyAdmission.admit>[0])=>{if(input.name==='replication-peer')throw Error('review peer unavailable');return p.dependencyAdmission.admit(input)}}};refused(bootProductionAssembly({...f.composition,production:q},x.manifest.id,x.binding.scope),'peer unavailable');expect(value(bootProductionAssembly({...f.composition,production:p},x.manifest.id,x.binding.scope)).owner).toBe('part-ten');});
it('V50 missing signed route reference refuses boot',()=>{const f=assemblyRuntimeFixture(),x=installProduction(f);const index=f.raw.findIndex(row=>(row as {kind?:string}).kind==='conversation-route');expect(index).toBeGreaterThanOrEqual(0);f.raw.splice(index,1);refused(bootProductionAssembly({...f.composition,production:productionComposition(f,x.binding)},x.manifest.id,x.binding.scope));});

// Keep the exact signed-subject controls adjacent to the imported review cases.
it('reviewer subject control: a correctly signed changed act digest still refuses',()=>{const f=intakeFixture(),v=f.verifiedAct();const changed=`sha256:${'0'.repeat(64)}`;const signed=f.f.proof({...v.challengePayload,actDigest:changed},{id:'alice',kind:'person'},'verified-operator-challenge');const proof=value(f.deps.capture.preserve(JSON.stringify({type:'VerifiedActProofBundle',schemaVersion:1,challenge:signed.input,act:v.actProof}),f.f.now));f.syncCaptures();refused(f.port().admitVerifiedAct({...v.input,proof}));});
