import type { VerificationRecord, VerificationRecordName } from '../../src/verification/index.js';

const common = (type: VerificationRecordName, id = type) => ({ type, schemaVersion: 1, id, predecessors: [] });
export const verificationInputs = {
  VerificationPlan: { ...common('VerificationPlan'),
    subject: { rules: [26], holder: 'verification-holder', governed: 'effect-operation', scope: 'conversation:1', generation: 'generation:1' },
    arms: [{ id: 'runtime', kind: 'runtime', executable: 'verification.runtime', fixture: 'P9-NF-09', outputContract: 'VerificationAssessment', canFail: 'stale evidence', required: true }],
    bar: { version: 'bar:1', predicates: ['occurrence', 'non-occurrence', 'quiescence', 'charge'], sources: ['destination'], minimumStrength: 'observation', subjectDigest: 'sha256:subject', captureRequired: true, freshness: 100, complete: true },
    independence: { testedPrincipal: 'agent', observerPrincipal: 'observer', witnessController: 'operator', commonFailures: ['shared destination compromise'] },
    scheduling: { owner: 'reviewer', run: 'run:1', loopPolicy: 'loop:1', cadence: 10, freshnessWindow: 100, dueAction: 'probe', recoveryBudget: 'budget:1' },
    bounds: [{ resource: 'attempts', limit: 2 }, { resource: 'money', limit: 0 }],
    consumers: [{ id: 'effect-settlement', direction: 'closed', enforcedRecord: 'VerificationAssessment', decoder: 'decodeVerificationAssessment', preserved: 'pending:1' }],
    privacy: { readers: ['reviewer'], providers: [], captureClass: 'judgment-local', secretCustody: 'vault', destinations: ['probe-target'] },
    activation: { unit: ['P9-NF-09'], integration: ['P9-NF-10'], lifecycle: ['P9-NF-12'], semantic: ['P9-NF-30'], limits: ['attempts=2'], evidence: ['check-run:1'] },
  },
  VerificationRequest: { ...common('VerificationRequest'), logicalKey: 'operation:1', operation: 'operation:1', attempt: 'attempt:1', reservation: 'reservation:1', operationDigest: 'sha256:operation', scope: 'conversation:1', predicate: 'occurrence', plan: 'VerificationPlan', barVersion: 'bar:1', initialEvidence: [], missingEvidence: ['destination-receipt'], owner: 'observer', loop: 'loop:1', createdAt: 10, sourceGeneration: 'generation:1' },
  VerificationAssessment: { ...common('VerificationAssessment'), request: 'VerificationRequest', operation: 'operation:1', attempt: 'attempt:1', operationDigest: 'sha256:operation', barVersion: 'bar:1', observer: 'observer', evidence: ['evidence:occurrence'], missingEvidence: ['complete-history'], vectorDigest: 'sha256:vector', knownLineages: ['machine-a'], captureStatuses: [{ reference: 'capture:1', status: 'available' }], taints: [], predicates: [
    { predicate: 'occurrence', verdict: 'satisfied', reason: 'authoritative destination receipt', evidence: ['evidence:occurrence'], decision: '' },
    { predicate: 'non-occurrence', verdict: 'contradicted', reason: 'receipt shows occurrence', evidence: ['evidence:occurrence'], decision: '' },
    { predicate: 'quiescence', verdict: 'insufficient', reason: 'executor may still run', evidence: [], decision: '' },
    { predicate: 'charge', verdict: 'insufficient', reason: 'final accounting missing', evidence: [], decision: '' },
  ], validFrom: 10, validUntil: 110, supersedes: '' },
  ProbeRecord: { ...common('ProbeRecord'), plan: 'VerificationPlan', planVersion: 'bar:1', slot: 'slot:1', attempt: 'attempt:1', subject: 'effect-operation', challengeDigest: 'sha256:challenge', run: 'run:1', operation: 'operation:probe', startedAt: 10, completedAt: 20, witnesses: ['evidence:witness'], comparison: 'Result:pass', disposition: 'passed', missingPhases: [], captureStatus: 'available', costs: [{ resource: 'money', amount: 0 }] },
  RetrospectiveReviewRecord: { ...common('RetrospectiveReviewRecord'), plan: 'VerificationPlan', reviewer: 'independent-reviewer', independenceEvidence: ['evidence:independence'], populationQuery: 'all-cases', vectorDigest: 'sha256:vector', sourceGeneration: 'generation:1', eligibleCases: ['case:1'], inspected: ['case:1'], omitted: [], sampling: { seed: 'seed:1', strata: ['refused'] }, modelAttempts: ['attempt:model'], decisions: ['decision:review'], findings: [], layerBelow: ['evidence:foundation'], nextWork: [], closure: 'converged', acceptedResidue: ['semantic inference remains'] },
  SemanticReviewRecord: { ...common('SemanticReviewRecord'), edge: 'rule:26->holder', generation: 'generation:1', ruleVersion: 'rule:26:v1', holderHash: 'sha256:holder', fixtureHash: 'sha256:fixture', decoderHash: 'sha256:decoder', checkRuns: ['check-run:1'], evidencePopulation: ['case:valid', 'case:invalid'], reviewer: 'independent-reviewer', decision: 'decision:semantic', coverageLimits: ['model judgment remains inference'], layerBelow: ['evidence:fixture'], compliantCases: ['case:valid'], violatingCases: ['case:invalid'], verdict: 'adequate' },
  Grade: { ...common('Grade'), benchmarkRecord: 'benchmark:case:1', request: 'judgment:request:1', resolution: 'judgment:resolution:1', decision: 'decision:1', criterion: 'criterion:1', planVersion: 'grade-plan:1', grader: 'independent-grader', gradingDecision: 'decision:grade', vectorDigest: 'sha256:vector', sourceGeneration: 'generation:1', inspected: ['decision:1'], missing: [], captureStatuses: [{ reference: 'capture:decision', status: 'available' }], taints: [], window: { start: 10, end: 20 }, conclusion: { assessment: 'supported', reason: 'evidence supports conclusion', evidence: ['evidence:1'] }, statedReason: { assessment: 'contradicted', reason: 'reason used a refuted premise', evidence: ['evidence:2'] }, outcome: { assessment: 'met', reason: 'observable subject met in window', evidence: ['evidence:3'] }, process: [{ requirement: 'floor', assessment: 'satisfied', reason: 'floor preserved', evidence: ['evidence:4'] }], completeness: { assessment: 'complete', missing: [], conflicts: [] }, supersedes: '' },
  AssessmentClosure: { ...common('AssessmentClosure'), caseId: 'case:1', sourceVectorDigest: 'sha256:vector', requiredAssessments: ['conclusion', 'reason', 'outcome', 'process'], dispositions: [
    { assessment: 'conclusion', disposition: 'assessed', reference: 'grade:1', reason: '' },
    { assessment: 'reason', disposition: 'assessed', reference: 'grade:1', reason: '' },
    { assessment: 'outcome', disposition: 'assessed', reference: 'grade:1', reason: '' },
    { assessment: 'process', disposition: 'assessed', reference: 'grade:1', reason: '' },
  ], activeDisputes: [], terminalResolutions: ['judgment:resolution:1'], settlements: ['effect:settlement:1'], reviewer: 'reviewer', decision: 'decision:closure', releasesPin: 'assessment-pin:case:1' },
  FeedbackDisposition: { ...common('FeedbackDisposition'), sourceIntent: 'intent:feedback:1', sourceCapture: 'capture:feedback:1', scope: 'conversation:1', detectionDecision: 'decision:feedback', explicitSubmission: '', relatedCases: ['case:1'], relatedClaims: [], relatedFindings: [], classification: 'failure-report', owner: 'improvement-owner', improvementRun: 'run:improvement', evidence: ['run-exit:improvement', 'regression:1'], nextDueAt: 100, disposition: 'verified-improvement', reason: '', duplicates: [] },
  BenchmarkEvaluation: { ...common('BenchmarkEvaluation'), benchmarkRun: 'benchmark-run:1', candidates: ['route:a'], scenarios: ['scenario:1'], executions: ['execution:1'], inputDigest: 'sha256:input', compatibilityDigest: 'sha256:compatibility', criterion: 'criterion:1', grades: ['grade:1'], missing: [], cancelled: [], refused: [], sampleSize: 1, heldOutGroups: [{ group: 'incident:1', sources: ['conversation:1'] }], costs: [{ resource: 'money', amount: 1 }], routeDecision: 'decision:route', selection: 'route:a', complete: true },
} as const satisfies Record<VerificationRecordName, object>;

export function verificationInput<N extends VerificationRecordName>(name: N): Extract<VerificationRecord, { type: N }> {
  return verificationInputs[name] as unknown as Extract<VerificationRecord, { type: N }>;
}
