import type ts from 'typescript';
export const DETECTOR_MODULES: readonly string[];
export function createProgram(extra?: Record<string, string>): ts.Program;
export function lintProgram(program: ts.Program, files: string[], detectors?: readonly string[]): { file: string; line: number; rule: string; detail: string }[];
export const INTENT_DECISION_SITES: Readonly<Record<string, { variables?: string[]; decisionProperties?: boolean; functions?: string[] }>>;
export function lintIntentSites(sources?: Record<string, string>): { file: string; line: number; rule: string; detail: string }[];
export const RETRIEVAL_SITES: Readonly<Record<string, { owner: string; adapter: string; rankers: string[]; entryPoints: string[]; advisory: string[] }>>;
export function lintRetrievalSites(sources?: Record<string, string>): { file: string; line: number; rule: string; detail: string }[];
type Issue = { file: string; line: number; rule: string; detail: string };
export const LIVE_ENTRY_POINTS: readonly string[];
export function shippedClientFiles(): string[];
export const HARNESS_ADAPTER_MODULES: readonly string[];
export function lintHarnessNames(sources: Record<string, string>): Issue[];
export function lintClientImports(sources: Record<string, string>): Issue[];
export const REPLACED_TRUTH_SOURCES: readonly { source: string; replacedBy: string; cutover: string }[];
export const DECLARED_OLD_STORE_READERS: Readonly<Record<string, string>>;
export const DYNAMIC_READERS: Readonly<Record<string, { loads: string[]; reason: string }>>;
export function lintReplacedStores(sources: Record<string, string>, liveEntries?: readonly string[],
  read?: (path: string) => string | null, exists?: (path: string) => boolean): Issue[];
export function registeredDoorways(text?: string): string[];
export function registerDeclarationSources(read?: (path: string) => string | null, root?: string): Record<string, unknown[]>;
export const NATIVE_HARNESS: string;
type ParityEvidence = { file: string; title: string };
type ParityCell = { status?: 'supported' | 'unsupported' | 'unproven'; declaredStates: string[]; inhibited?: true;
  evidence?: ParityEvidence[]; reason?: string; artifact?: string[]; route?: string[]; source: string; declaration: string };
export function parityMatrix(sources?: Record<string, unknown>): { type: 'ParityMatrix'; derivedFrom: string[]; channels: string[];
  features: { id: string; cells: Record<string, ParityCell & { feature: string; channel: string }> }[];
  harnessTuples: (ParityCell & { harness: string; doorway: string; platform: string; mode: string })[]; stray: string[] };
export function lintParityRegister(sources?: Record<string, unknown>, read?: (path: string) => string | null,
  doorways?: readonly string[]): Issue[];
